// Generated by Xata Codegen 0.21.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "selam",
    columns: [
      { name: "company", type: "string" },
      { name: "title", type: "string" },
      { name: "jobLink", type: "string" },
      { name: "location", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Selam = InferredTypes["selam"];
export type SelamRecord = Selam & XataRecord;

export type DatabaseSchema = {
  selam: SelamRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Erdogan-Cayir-s-workspace-jjjh4n.us-east-1.xata.sh/db/first",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
